// This file create dummy function to please the linker for managed plugin compatibility

void version() {}
void LUA_MULTRET() {}
void LuaTypeName() {}
void abs_index() {}
void luaL_argerror() {}
void luaL_callmeta() {}
void luaL_checkany() {}
void luaL_checkboolean() {}
void luaL_checkinteger() {}
void luaL_checklstring() {}
void luaL_checknumber() {}
void luaL_checkstack() {}
void luaL_checktype() {}
void luaL_checkudata() {}
void luaL_dofile() {}
void luaL_dostring() {}
void luaL_findtable() {}
void luaL_getmetafield() {}
void luaL_getmetatable() {}
void luaL_getn() {}
void luaL_getversion() {}
void luaL_gsub() {}
void luaL_loadbuffer() {}
void luaL_loadbufferx() {}
void luaL_loadfile() {}
void luaL_loadfilex() {}
void luaL_loadstring() {}
void luaL_newmetatable() {}
void luaL_newstate() {}
void luaL_openlibs() {}
void luaL_optinteger() {}
void luaL_optlstring() {}
void luaL_optnumber() {}
void luaL_ref() {}
void luaL_requiref() {}
void luaL_throw() {}
void luaL_typename() {}
void luaL_typerror() {}
void luaL_unref() {}
void luaL_where() {}
void luaopen_cjson() {}
void luaopen_cjson_safe() {}
void luaopen_lpeg() {}
void luaopen_mime_core() {}
void luaopen_pb() {}
void luaopen_socket_core() {}
void luaopen_struct() {}
void lua_atpanic() {}
void lua_call() {}
void lua_callk() {}
void lua_checkstack() {}
void lua_close() {}
void lua_compare() {}
void lua_concat() {}
void lua_cpcall() {}
void lua_createtable() {}
void lua_equal() {}
void lua_gc() {}
void lua_getfield() {}
void lua_getgccount() {}
void lua_getglobal() {}
void lua_gethook() {}
void lua_gethookcount() {}
void lua_gethookmask() {}
void lua_getinfo() {}
void lua_getlocal() {}
void lua_getmetatable() {}
void lua_getref() {}
void lua_getregistry() {}
void lua_getstack() {}
void lua_gettable() {}
void lua_gettop() {}
void lua_getupvalue() {}
void lua_getuservalue() {}
void lua_insert() {}
void lua_isboolean() {}
void lua_iscfunction() {}
void lua_isfunction() {}
void lua_isinteger() {}
void lua_islightuserdata() {}
void lua_isnil() {}
void lua_isnone() {}
void lua_isnoneornil() {}
void lua_isnumber() {}
void lua_isstring() {}
void lua_istable() {}
void lua_isthread() {}
void lua_isuserdata() {}
void lua_lessthan() {}
void lua_newtable() {}
void lua_newthread() {}
void lua_newuserdata() {}
void lua_next() {}
void lua_objlen() {}
void lua_open() {}
void lua_pcall() {}
void lua_pcallk() {}
void lua_pop() {}
void lua_ptrtostring() {}
void lua_pushboolean() {}
void lua_pushcclosure() {}
void lua_pushcfunction() {}
void lua_pushglobaltable() {}
void lua_pushinteger() {}
void lua_pushlightuserdata() {}
void lua_pushlstring() {}
void lua_pushnil() {}
void lua_pushnumber() {}
void lua_pushstring() {}
void lua_pushthread() {}
void lua_pushvalue() {}
void lua_rawequal() {}
void lua_rawget() {}
void lua_rawgeti() {}
void lua_rawset() {}
void lua_rawseti() {}
void lua_ref() {}
void lua_register() {}
void lua_remove() {}
void lua_replace() {}
void lua_resume() {}
void lua_setfield() {}
void lua_setglobal() {}
void lua_sethook() {}
void lua_setlocal() {}
void lua_setmetatable() {}
void lua_settable() {}
void lua_settop() {}
void lua_setupvalue() {}
void lua_setuservalue() {}
void lua_status() {}
void lua_toboolean() {}
void lua_tocfunction() {}
void lua_tointeger() {}
void lua_tointegerx() {}
void lua_tolstring() {}
void lua_tonumber() {}
void lua_tonumberx() {}
void lua_topointer() {}
void lua_tostring() {}
void lua_tothread() {}
void lua_touserdata() {}
void lua_type() {}
void lua_typename() {}
void lua_unref() {}
void lua_upvalueindex() {}
void lua_xmove() {}
void lua_yieldk() {}
void toluaL_exception() {}
void toluaL_ref() {}
void toluaL_unref() {}
void tolua_addchar() {}
void tolua_addlstring() {}
void tolua_addpreload() {}
void tolua_addstring() {}
void tolua_argerror() {}
void tolua_beginclass() {}
void tolua_beginenum() {}
void tolua_beginmodule() {}
void tolua_beginpcall() {}
void tolua_beginpremodule() {}
void tolua_beginstaticclass() {}
void tolua_bindthis() {}
void tolua_buffinit() {}
void tolua_checkint64() {}
void tolua_checkuint64() {}
void tolua_constant() {}
void tolua_createtable() {}
void tolua_endclass() {}
void tolua_endenum() {}
void tolua_endmodule() {}
void tolua_endpremodule() {}
void tolua_endstaticclass() {}
void tolua_error() {}
void tolua_findtable() {}
void tolua_fixedupdate() {}
void tolua_freebuffer() {}
void tolua_function() {}
void tolua_getclassref() {}
void tolua_getclr() {}
void tolua_getfield() {}
void tolua_getlayermask() {}
void tolua_getmainstate() {}
void tolua_getmetatableref() {}
void tolua_getn() {}
void tolua_getquat() {}
void tolua_gettable() {}
void tolua_getvaluetype() {}
void tolua_getvec2() {}
void tolua_getvec3() {}
void tolua_getvec4() {}
void tolua_isint64() {}
void tolua_isuint64() {}
void tolua_isvptrtable() {}
void tolua_lateupdate() {}
void tolua_loadbuffer() {}
void tolua_newudata() {}
void tolua_newuserdata() {}
void tolua_objlen() {}
void tolua_openint64() {}
void tolua_openlibs() {}
void tolua_openlualibs() {}
void tolua_pushcfunction() {}
void tolua_pushclr() {}
void tolua_pushint64() {}
void tolua_pushlayermask() {}
void tolua_pushlstring() {}
void tolua_pushluatable() {}
void tolua_pushnewudata() {}
void tolua_pushquat() {}
void tolua_pushresult() {}
void tolua_pushtraceback() {}
void tolua_pushudata() {}
void tolua_pushuint64() {}
void tolua_pushvec2() {}
void tolua_pushvec3() {}
void tolua_pushvec4() {}
void tolua_rawnetobj() {}
void tolua_regthis() {}
void tolua_require() {}
void tolua_setfield() {}
void tolua_setflag() {}
void tolua_setindex() {}
void tolua_setnewindex() {}
void tolua_settable() {}
void tolua_strlen() {}
void tolua_tag() {}
void tolua_toboolean() {}
void tolua_tocbuffer() {}
void tolua_toint64() {}
void tolua_tointeger() {}
void tolua_tolstring() {}
void tolua_touint64() {}
void tolua_update() {}
void tolua_variable() {}
void tolua_where() {}